var gis_engine_url="http://192.168.0.71:8092/G2DataService/GService?",myLayout,mainLayout,mainGrid,map,baseLayer,_layers=[],_currentEditLayer=null,headerCell=null,categoryCell=null,propertyCell=null,editControls=null,panel=null,selectControl=null,DeleteFeature=new OpenLayers.Class(OpenLayers.Control,{initialize:function(a,d){OpenLayers.Control.prototype.initialize.apply(this,[d]);this.layer=a;this.handler=new OpenLayers.Handler.Feature(this,a,{click:this.clickFeature})},clickFeature:function(a){void 0==
a.fid?this.layer.destroyFeatures([a]):(a.state=OpenLayers.State.DELETE,this.layer.events.triggerEvent("afterfeaturemodified",{feature:a}),a.renderIntent="select",this.layer.drawFeature(a))},setMap:function(a){this.handler.setMap(a);OpenLayers.Control.prototype.setMap.apply(this,arguments)},CLASS_NAME:"OpenLayers.Control.DeleteFeature"});
function initLayout(){myLayout=new dhtmlXLayoutObject({parent:document.body,pattern:"5I",skin:"dhx_skyblue",offsets:{top:10,right:10,bottom:10,left:10},cells:[{id:"a",header:!1,height:40,fix_size:[null,!0]},{id:"b",text:"\uce35 \uc120\ud0dd",header:!0,width:150},{id:"c",text:"\ub3c4\uba74",header:!1},{id:"d",text:"\uc18d\uc131\uc815\ubcf4",header:!0,width:200,collapse:!0},{id:"e",text:"\uc870\ud68c \ub370\uc774\ud130",header:!1,width:200,collapse:!0}]});headerCell=myLayout.cells("a");categoryCell=
myLayout.cells("b");propertyCell=myLayout.cells("d");mainGrid=myLayout.cells("e").attachGrid();mainGrid.setImagePath(context_root+"/js/codebase/imgs/");mainGrid.setHeader("ID,\uacf5\uac04 \uc815\ubcf4 \uba85,\uaddc\uaca9,\ub4f1\ub85d\uc790,\ub4f1\ub85d\uc77c,\uc218\uc815\uc790,\uc218\uc815\uc77c\uc790");mainGrid.setInitWidths("100,250,300,100,120,100,120,100");mainGrid.setColAlign("right,center,center,center,center,center,center");mainGrid.setColTypes("ro,ro,ro,ro,ro,ro,ro,ro");mainGrid.setColSorting("int,str,str,str,str,str,str");
mainGrid.init()}
function initMap(a,d,c,e){var g=new OpenLayers.Bounds(e[0],e[1],e[2],e[3]);OpenLayers.ImgPath=context_root+"/images/egovframework/ygpa/gam/maps/";OpenLayers.theme=context_root+"/js/theme/ygpa/";Proj4js.libPath=context_root+"/js/Proj4js/";$("#div_map").height(myLayout.cells("c").getHeight());myLayout.cells("c").attachObject("div_map");myLayout.cells("c").progressOn();map=new OpenLayers.Map({div:"div_map",allOverlays:!0,maxExtent:g,srsName:"EPSG:5186"});var h=new OpenLayers.StyleMap({"default":{strokeColor:"#000000",strokeOpacity:1,
strokeWidth:1,fillColor:"#FBFF9A",fillOpacity:0.5,pointRadius:6,pointerEvents:"visiblePainted",fontColor:"black",fontSize:"12px",fontFamily:"Courier New, monospace",fontWeight:"bold",labelAlign:"cm",labelXOffset:"2px",labelYOffset:"2px",labelOutlineColor:"white",labelOutlineWidth:3},select:{strokeColor:"#00FF00",strokeOpacity:1,strokeWidth:3,fillColor:"#E92FFF",fillOpacity:1,pointRadius:6,pointerEvents:"visiblePainted",fontColor:"white",fontSize:"12px",fontFamily:"Courier New, monospace",fontWeight:"bold",
labelAlign:"cm",labelXOffset:"2px",labelYOffset:"2px",labelOutlineColor:"black",labelOutlineWidth:3}}),k=new OpenLayers.StyleMap({"default":{strokeColor:"#FF00FF",strokeOpacity:1,strokeWidth:1,fillColor:"#00009A",fillOpacity:0.5,pointRadius:6,pointerEvents:"visiblePainted",fontColor:"black",fontSize:"12px",fontFamily:"Courier New, monospace",fontWeight:"bold",labelAlign:"cm",labelXOffset:"2px",labelYOffset:"2px",labelOutlineColor:"white",labelOutlineWidth:3},select:{strokeColor:"#00FF00",strokeOpacity:1,
strokeWidth:3,fillColor:"#E92FFF",fillOpacity:1,pointRadius:6,pointerEvents:"visiblePainted",fontColor:"white",fontSize:"12px",fontFamily:"Courier New, monospace",fontWeight:"bold",labelAlign:"cm",labelXOffset:"2px",labelYOffset:"2px",labelOutlineColor:"black",labelOutlineWidth:3}});baseLayerProtocol=new OpenLayers.Protocol.WFS.v1_1_0({version:"1.1.0",service:"WFS",url:gis_engine_url,filter:new OpenLayers.Filter.Comparison({type:OpenLayers.Filter.Comparison.EQUAL_TO,property:"Layer",value:name}),
featureNS:"http://geogate.g-inno.com/dataserver/datahouse",featurePrefix:"datahouse",featureType:a,srsName:"EPSG:5186",geometryName:"G2_SPATIAL"});$.each(c,function(b,c){var d=new OpenLayers.Layer.Vector(c.name,{projection:new OpenLayers.Projection("EPSG:5186"),displayInLayerSwitcher:!1,isBaseLayer:!1,strategies:[new OpenLayers.Strategy.BBOX],protocol:new OpenLayers.Protocol.WFS({version:"1.1.0",service:"WFS",url:gis_engine_url,featureNS:"http://geogate.g-inno.com/dataserver/datahouse",featurePrefix:"datahouse",
featureType:a,srsName:"EPSG:5186",geometryName:"G2_SPATIAL"}),filter:new OpenLayers.Filter.Comparison({type:OpenLayers.Filter.Comparison.EQUAL_TO,property:"FL",value:c.layer}),maxExtent:g,styleMap:h});d._floor=c.layer;d.events.register("loadend",myLayout.cells("c"),function(b){this.progressOn()});d.events.register("loadend",myLayout.cells("c"),function(b){this.progressOff()});_layers[_layers.length]=d});var b=[];$.each(c,function(a,c){var e=new OpenLayers.Strategy.Save,f=new OpenLayers.Layer.Vector(c.name,
{projection:new OpenLayers.Projection("EPSG:5186"),displayInLayerSwitcher:!1,isBaseLayer:!1,strategies:[e,new OpenLayers.Strategy.BBOX],protocol:new OpenLayers.Protocol.WFS({version:"1.1.0",service:"WFS",url:gis_engine_url,featureNS:"http://geogate.g-inno.com/dataserver/datahouse",featurePrefix:"datahouse",featureType:d,srsName:"EPSG:5186",geometryName:"G2_SPATIAL"}),filter:new OpenLayers.Filter.Comparison({type:OpenLayers.Filter.Comparison.EQUAL_TO,property:"FL",value:c.layer}),maxExtent:g,styleMap:k});
f._floor=c.layer;f._editLayer=!0;f._saveStrategy=e;f._saveStrategy.events.register("success",map,function(b){alert("\uc800\uc7a5 \ub418\uc5c8\uc2b5\ub2c8\ub2e4.")});f._saveStrategy.events.register("fail",map,function(b){alert("\uc800\uc7a5 \uc2e4\ud328 \ud558\uc600\uc2b5\ub2c8\ub2e4.")});f.events.register("beforefeatureselected",map,function(b){selectControl.unselectAll()});f.events.register("featureselected",map,function(b){this.events.triggerEvent("featureselected",b.feature)});f.events.register("featureunselected",
map,function(b){this.events.triggerEvent("featureunselected",b.feature)});b[b.length]=f;_layers[_layers.length]=f});var f=c[0].layer;map.addLayers(_layers);$.each(_layers,function(b,a){a._floor==f?(a.setVisibility(!0),a._editLayer&&(_currentEditLayer=a)):a.setVisibility(!1)});selectControl=new OpenLayers.Control.SelectFeature(b,{clickout:!0,toggle:!0,multiple:!0,hover:!1,multipleKey:"shiftKey"});selectControl.handlers.feature.stopDown=!1;map.addControls([new OpenLayers.Control.MousePosition({prefix:"\uc9c0\ub3c4 \uc88c\ud45c : ",
separator:" | ",numDigits:6,displayProjection:new OpenLayers.Projection("EPSG:5186")}),new OpenLayers.Control.Scale,selectControl]);selectControl.activate();map.zoomToExtent(g);return map}function switchFloor(a){$.each(_layers,function(a,c){!0==c.getVisibility()&&c.setVisibility(!1)});$.each(_layers,function(d,c){c._floor==a&&(c.setVisibility(!0),!0==c._editLayer&&(_currentEditLayer=c))})}
function editLayer(){var a=_currentEditLayer;editControls={addPoint:new OpenLayers.Control.DrawFeature(a,OpenLayers.Handler.Point,{featureAdded:function(b){console.log("add point");b.attributes.FL=this.layer._floor;this.layer!=b.layer&&this.layer.addFeatures([b])}}),addLine:new OpenLayers.Control.DrawFeature(a,OpenLayers.Handler.Path,{featureAdded:function(b){console.log("add line");b.attributes.FL=this.layer._floor;this.layer!=b.layer&&this.layer.addFeatures([b])}}),addFeature:new OpenLayers.Control.DrawFeature(a,
OpenLayers.Handler.Polygon,{featureAdded:function(b){console.log("add feature");b.attributes.FL=this.layer._floor;this.layer!=b.layer&&this.layer.addFeatures([b])}}),editFeature:new OpenLayers.Control.ModifyFeature(a,{vertexRenderIntent:"modify",virtualStyle:{strokeColor:"#00ff00",fillColor:"#00ff00",strokeOpacity:1,strokeWidth:2,pointRadius:5,graphicName:"triangle"},mode:OpenLayers.Control.ModifyFeature.RESHAPE,handlerOptions:{holeModifier:"altKey"}}),delFeature:new DeleteFeature(a,{title:"\uc0ad\uc81c"})};
for(var d in editControls)map.addControl(editControls[d]);d=new OpenLayers.Control.Button({title:"\uc810 \ucd94\uac00",displayClass:"olControlEditAddPoint",type:OpenLayers.Control.TYPE_TOGGLE,eventListeners:{activate:function(){for(var b in editControls)"addPoint"!=b&&editControls[b].button.deactivate();editControls.addPoint.activate()},deactivate:function(){for(var b in editControls){var a=editControls[b];"addPoint"==b&&a.deactivate()}}}});editControls.addPoint.button=d;var c=new OpenLayers.Control.Button({title:"\uc120 \ucd94\uac00",
displayClass:"olControlEditAddLine",type:OpenLayers.Control.TYPE_TOGGLE,eventListeners:{activate:function(){for(var b in editControls)"addLine"!=b&&editControls[b].button.deactivate();editControls.addLine.activate()},deactivate:function(){for(var b in editControls){var a=editControls[b];"addLine"==b&&a.deactivate()}}}});editControls.addLine.button=c;var e=new OpenLayers.Control.Button({title:"\ucd94\uac00",displayClass:"olControlEditAdd",type:OpenLayers.Control.TYPE_TOGGLE,eventListeners:{activate:function(){for(var b in editControls)"addFeature"!=
b&&editControls[b].button.deactivate();editControls.addFeature.activate()},deactivate:function(){for(var b in editControls){var a=editControls[b];"addFeature"==b&&a.deactivate()}}}});editControls.addFeature.button=e;var g=new OpenLayers.Control.Button({title:"\ud3b8\uc9d1",displayClass:"olControlEditEdit",type:OpenLayers.Control.TYPE_TOGGLE,eventListeners:{activate:function(){for(var b in editControls)"editFeature"!=b&&editControls[b].button.deactivate();editControls.editFeature.activate()},deactivate:function(){for(var b in editControls){var a=
editControls[b];"editFeature"==b&&a.deactivate()}}}});editControls.editFeature.button=g;var h=new OpenLayers.Control.Button({title:"\uc0ad\uc81c",displayClass:"olControlEditDelete",type:OpenLayers.Control.TYPE_TOGGLE,eventListeners:{activate:function(){for(var b in editControls)"delFeature"!=b&&editControls[b].button.deactivate();editControls.delFeature.activate()},deactivate:function(){for(var b in editControls){var a=editControls[b];"delFeature"==b&&a.deactivate()}}}});editControls.delFeature.button=
h;var a=new OpenLayers.Control.Button({title:"\ud3b8\uc9d1 \uc644\ub8cc",layer:a,trigger:function(){panel.deactivate();map.removeControl(panel);for(var a in editControls)editControls[a].deactivate();selectControl.activate();this.layer._saveStrategy.save()},displayClass:"olControlEditDone"}),k=new OpenLayers.Control.Button({title:"\ud3b8\uc9d1 \ucde8\uc18c",trigger:function(){panel.deactivate();map.removeControl(panel);for(var a in editControls)editControls[a].deactivate();selectControl.activate()},
displayClass:"olControlEditCancel"});null!=panel&&panel.deactivate();panel=new OpenLayers.Control.Panel({displayClass:"mapEditToolBar"});selectControl.deactivate();panel.addControls([d,c,e,g,h,a,k]);map.addControl(panel);panel.activate()}function leftPad(a,d,c){var e="";a=a.toString();if(a.length<c)for(var g=0;g<c-a.length;g++)e+=d;return e+a}function getDate(a){null==a&&(a=new Date);return leftPad(a.getFullYear(),"0",4)+"-"+leftPad(a.getMonth()+1,"0",2)+"-"+leftPad(a.getDate(),"0",2)}
function saveFeature(a){null!=_currentEditLayer&&(a.state!=OpenLayers.State.INSERT?(a.state=OpenLayers.State.UPDATE,a.attributes.UPD_DT=getDate()):a.attributes.REG_DT=getDate(),_currentEditLayer._saveStrategy.save())};
